"""Agrega restricciones a detalle de venta

Revision ID: 4ea3c730091b
Revises: 
Create Date: 2026-10-05 11:52:49.009295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea3c730091b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_detalle_cantidad_positiva",
        "detalle_ventas",
        "cantidad > 0"
    )

    op.create_check_constraint(
        "ck_detalle_precio_no_negativo",
        "detalle_ventas",
        "precio_unitario >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_detalle_precio_no_negativo",
        "detalle_ventas",
        type_="check"
    )

    op.drop_constraint(
        "ck_detalle_precio_no_negativo",
        "detalle_ventas",
        type_="check"
    )
    # ### end Alembic commands ###
