"""Agrega movimientos de inventario

Revision ID: 53f2435096da
Revises: 4ea3c730091b
Create Date: 2026-10-09 13:20:57.603841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f2435096da'
down_revision: Union[str, Sequence[str], None] = '4ea3c730091b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='ck_movimiento_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_inventario')
    # ### end Alembic commands ###
